name: 'Integration-Tests'
on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run package
      - name: Test success
        uses: ./
        with:
          target-repo: s-weigand/flake8-nb
          debug: true
      - name: Test custom build server
        continue-on-error: true
        uses: ./
        with:
          target-repo: s-weigand/flake8-nb
          use-default-build-servers: false
          additional-build-servers: |
            foo
          debug: true
      - name: Test fail
        continue-on-error: true
        uses: ./
        with:
          target-repo: s-weigand/flake8-nb
          target-state: not-a-branch
          debug: true
