name: 'Tests'
on: [push, pull_request]

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run build
      - name: Checking format
        run: npm run format-check
      - name: Linting code
        run: npm run lint
      - name: Running jest tests
        run: npm test

  release-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Create fresh build release  compare file
        run: npm run release-compare-file
      - name: Test if the release and compare file are different
        run: diff -ywBd --suppress-common-lines dist/index.js compare/index.js

  test-integration:
    runs-on: ${{ matrix.os }}
    needs: [jest-tests, release-up-to-date]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Build index.js
        run: npm run release
      - uses: ./
        with:
          target-repo: s-weigand/ipynb-share
